### ISSUE TITLE
Formatter breaks with internal behave API with behave > 1.2.6.

### ISSUE THREAD

**Issue by Kory291** [behave-contrib/behave-html-pretty-formatter#94]
Hi all,

yesterday after receiving an update of behave to 1.3.0 I got the following error message:

> $ behave --junit --junit-directory=junit_reports --no-skipped --tags=-ignore $BEHAVE_FEATURES
USING RUNNER: behave.runner:Runner
Exception AttributeError: 'NoneType' object has no attribute 'add_scenario'
Traceback (most recent call last):
  File ".../.venv/bin/behave", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File ".../.venv/lib/python3.13/site-packages/behave/__main__.py", line 291, in main
    return run_behave(config)
  File ".../.venv/lib/python3.13/site-packages/behave/__main__.py", line 113, in run_behave
    failed = runner.run()
  File ".../.venv/lib/python3.13/site-packages/behave/runner.py", line 1138, in run
    return self.run_with_paths()
           ~~~~~~~~~~~~~~~~~~~^^
  File ".../.venv/lib/python3.13/site-packages/behave/runner.py", line 1158, in run_with_paths
    return self.run_model()
           ~~~~~~~~~~~~~~^^
  File ".../.venv/lib/python3.13/site-packages/behave/runner.py", line 940, in run_model
    failed = feature.run(self)
  File ".../.venv/lib/python3.13/site-packages/behave/model.py", line 424, in run
    failed = run_item.run(runner)
  File ".../.venv/lib/python3.13/site-packages/behave/model.py", line 1697, in run
    failed = scenario.run(runner)
  File ".../.venv/lib/python3.13/site-packages/behave/model.py", line 1162, in run
    formatter.scenario(self)
    ~~~~~~~~~~~~~~~~~~^^^^^^
  File ".../.venv/lib/python3.13/site-packages/behave_html_pretty_formatter/html_pretty.py", line 1348, in scenario
    self.current_feature.add_scenario(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'add_scenario'

Is it in a first solution possible to limit the newest version of the formatter to behave <=1.2.6?

I used behave 1.3.0 and behave-pretty-html-formatter 1.14.1.

Thank you for your help :)

**Comment by fpokryvk** [comment]
Hi, 

we also see some other fixes html-pretty fotmatter needs to work correctly with new behave release. Thank you for the report, I will investigate and try to fix.

Maybe an example of feature file producing exception above would also help, so we are sure this is properly fixed.

**Comment by modehnal** [comment]
Hello,

yes, the behave got updated yesterday to version 1.3.0 and it breaks a lot of stuff on our side.

Current solution is to fix your version of behave to `behave==1.2.6` until we fix the formatter for the new version.

I see that the formatter has the behave not fixed so it will pull the newest behave, so perhaps fixing the formatter version for behave 1.2.6 might be fixed to at least prevent some issues.

Filip or I will take a look at it when possible.

**Comment by Kory291** [comment]
Hi,

one example would be:
```gherkin
Feature: Get Device by name

  Scenario: Get Device by Name
    Given EMS "placeholder"
    And the user uses the device "placeholder"
    When REST call is made "Get device by name v1a"
    Then the status code should be 200

  Scenario: Get Device by false Name
    Given EMS "placeholder"
    And the user uses the device "placeholder"
    When REST call is made "Get device by name v1a"
    Then the status code should be 204
```

But we also have some that use the `Scenario Outline` which also failed.

**Comment by bittner** [comment]
If the old 1.2.6 version runs fine, good. I'd suggest to pin a recent dev-version otherwise. The latest might cause some issue, but maybe 1.2.7.dev7 or dev6 will work.

Also, see https://github.com/behave/behave-django/issues/158 (and similar) for related issues known for some time. We all need to work towards a stable API for the contrib projects not to get into trouble continously.

**Comment by Kory291** [comment]
I pinned it to 1.2.6. so now I have a workaround.

**Comment by modehnal** [comment]
I released 1.14.2 with fixed behave to 1.2.6 before we fix the compatibility issues with behave 1.3.0.

**Comment by modehnal** [comment]
I will reopen this though, this is not solved.

**Comment by jenisys** [comment]
In the `PrettyHTMLFormatter` class:

* The `self.current_feature` attribute uses the last item of `self.features` which was added in the `…Formatter.feature()` method.
* The problem occurs in the `…Formatter.scenario()` method where the `feature()` method should have been already called.

**Comment by jenisys** [comment]
@Kory291 
When I run `behave -f html-pretty -o report.html features/tags*.feature`,
I get a normal HTML report and everything is fine.
Same case, if I run behave against the `features/` directory in `behave` with the `html-pretty` formatter.

* Using `behave-html-pretty-formatter v1.14.1`
* Using `behave v1.3.0`
* Using Python 3.12 on macOS (but Python 3.13 should also work)

QUESTIONS:

* Can you run behave with the `html-pretty` formatter against the `features/` directory of the `behave` repo ?

```shell
# — ENSURE:
# behave v1.3.0
# behave-html-pretty-formatter v1.14.1
$ behave -f html-pretty -o report.html -f progress features/
```

SEE ALSO:

* https://github.com/behave/behave

**Comment by Kory291** [comment]
@jenisys 
I just did what you did and now I got an HTML report. The problem is that it dsiplays all of the steps in a scenario, but fails after the first step in the scenario. In my terminal I still get the same error message as posted above.

As command I used `behave -f html-pretty -o test-file.html features`.
I used `behave v1.3.0` and `behave-html-pretty-formatter v1.14.1` on WSL with Ubuntu 24.04. I used both Python 3.13.5 and 3.12.7. But still the error was the same.

Also note, I had an immediate error before, because in our project we set up the PrettyHTMLFormatter in the `environment.py` if it was not added directly with parameters of behave. This was at the time of implementation the only way I found of getting the PrettyHTMLFormmater to work together with PyCharms Behave Plugin.
For the test run now, I commented this and just the command above.

Are there any more differences to think about?

**Comment by fpokryvk** [comment]
What I noticed is that behave-1.3.0 calls `scenario()` in different time - I think now it is before `before_scenario()`, but it was after `before_scenario()` in behave-1.2.6 - so formatter might not work in all cases well with this change, and some `NoneType` exception might pop-up due to this change.

Also, I have noticed if we do skip in `before_scenario()`, the scenario is twice in HTML, once as untested and once as skipped. This is because since 1.3.0 behave calls `scenario()` again with `status.Skipped`. Again, we need to treat this correctly. 

However, as @bittner mentioned, those changes are hard to maintain, so we have to probably freeze the formatter version for behave-1.2.6 as it is now, and new releases of the html-pretty formatter will be compatible only with behave-1.3.0+ (as detecting the behave API on the fly in the code is not a good idea).

**Comment by jenisys** [comment]
@Kory291 
> [@jenisys](https://github.com/jenisys) I just did what you did and now I got an HTML report. The problem is that it dsiplays all of the steps in a scenario, but fails after the first step in the scenario. In my terminal I still get the same error message as posted above.
> 
> As command I used `behave -f html-pretty -o test-file.html features`. I used `behave v1.3.0` and `behave-html-pretty-formatter v1.14.1` on WSL with Ubuntu 24.04. I used both Python 3.13.5 and 3.12.7. But still the error was the same.
> 
> Also note, I had an immediate error before, because in our project we set up the PrettyHTMLFormatter in the `environment.py` if it was not added directly with parameters of behave. This was at the time of implementation the only way I found of getting the PrettyHTMLFormmater to work together with PyCharms Behave Plugin. For the test run now, I commented this and just the command above.

OOPS, you fiddle and add a formatter in „environment.py“ ?!
* You should never ever add a formatter there !!!

> Are there any more differences to think about?

You need to provide a minimal example that is causing your problem.
Currently, I can‘t help you because I cannot replicate your findings.
And do not know if @modehnal can reproduce it.

**Comment by jenisys** [comment]
@fpokryvk 
> What I noticed is that behave-1.3.0 calls `scenario()` in different time - I think now it is before `before_scenario()`, but it was after `before_scenario()` in behave-1.2.6 - so formatter might not work in all cases well with this change, and some `NoneType` exception might pop-up due to this change.
> 
> Also, I have noticed if we do skip in `before_scenario()`, the scenario is twice in HTML, once as untested and once as skipped. This is because since 1.3.0 behave calls `scenario()` again with `status.Skipped`. Again, we need to treat this correctly.

* The ordering of the `Formatter.scenario()` method call and the `before_scenario()` hook changed in `behave v1.2.7.dev7`.
* BUT: The `Formatter.scenario()` method is only called once for each scenario
* What the Formatter makes out of it when the next `Formatter.scenario()` is called with the next scenario, is something completely different. Because at that point you know the result of the current scenario (inside the Formatter) before the next scenario is started.

**Comment by modehnal** [comment]
Apologies, there are currently more things on fire, but I will try to test the formatter as soon as possible.

**Comment by Kory291** [comment]
@jenisys From experience this was save to do. However that broke with the update.

I set up something small which causes the error ([here](https://github.com/Kory291/behave-pretty-html-formatter-test)). The error happens if I try to set up another formatter in the `before_feature` function.
We did this in our project, because a tester had problem if he ran multiple features and complained that he couldn't understand the report. So we also generated a new HTML report based on the feature.

How should we procede with this?

**Comment by jenisys** [comment]
@Kory291 
I used your small repo. BUT: I do not run into any error.

```bash
# — GENERATES: first.html — HACK from environment
behave -f progress3 features

# — GENERATES: report.html
behave -f html-pretty -o report.html -f progress3 features

# — SAME WITH:
behave -f plain features
behave -f pretty features
```

* What is the failure syndrome that you are observing ?

USING:

* Python 3.12.x

NOTES:
* As already stated: Adding formatters in `before_all()` hook is a hack
* Use `behave` as it is intended.
* FOR EXAMPLE: Specify your formatters and outputs in the `behave.ini` config-file like: [behave.ini](https://github.com/behave/behave/blob/main/behave.ini#L15)
* That allows you to select other formatter(s) on the command-line and still use the formatters/reports from the config-file.

**Comment by jenisys** [comment]
@Kory291 
OK, I have enabled the commented-out block in the `before_feature()` hook.
Now I see your syndrome.

BUT:
* Do not do stupid things and you will not have any problems.
* Or as a German saying: „Small sins are often immediately punished by God (and sometimes later)“.

**Comment by jenisys** [comment]
@Kory291 
OK, I debugged it.

PROBLEM IS CAUSED BY: By your own wrong doing

* The second html-pretty formatter that was added in the `before_feature()` hook, was never called with `Formatter.feature()` because it was registered too late.
* Therefore, you run into this NULL-POINTER-PROBLEM (or: None) for the `self.current_feature`

**Comment by jenisys** [comment]
@Kory291 
* I provided a solution to your "hack" for `behave v1.3.0`
* BUT: In my opinion, you solved the wrong problem or you solved the problem in a wrong way.

SEE ALSO:

* https://github.com/Kory291/behave-pretty-html-formatter-test/pull/1

REAL SOLUTION:
* Select a HTML formatter that suits your needs: 
  One HTML file for each feature (and a summary HTML file for the complete test run)
* Make an enhancement request to this repo that it supports such a report structure (see line above)
* Adapt and extend an existing formatter to fulfil your needs and use it.
  NOTE: Formatters are an extension-point in `behave` and you can use multiple ones if needed.
* Write your own HTML formatter that fulfils you needs.

HINTS:
* Use `behave.ini` config-file to always use formatter/output combinations independent of the command-line formatter or default-formatter (for PyCharm or other IDEs/editors).

**Comment by Kory291** [comment]
@jenisys Thanks for the solution. That should do the trick for now.

Adapting this formatter would probably be the better solution.

Regarding your comment with `behave.ini`: I tried that when I faced the problem. Back then it wasn't setting up the formatter. Only the formatter that PyCharms Behave plugin used was available.

Can we close this issue then?

**Comment by modehnal** [comment]
>  Can we close this issue then?

Not yet we are aware of a few things that need changing but did not have time to do it.

I did not read the backlog here properly, but if there is something you would like to change let us know. If there is a proper usage that you want supported by this formatter, I am not against it.

**Comment by modehnal** [comment]
So @fpokryvk solved his issue that he saw in his reports, my reports seem to be fine as well with new behave and latest formatter version. 

From what @jenisys explained, the usage was wrong and should not be used that way. But I see no harm to provide a way to register it late within this formatter. So if I understand it correctly, you should still be able to use it as you do @Kory291 with the commit https://github.com/behave-contrib/behave-html-pretty-formatter/pull/97/commits/b287723b53dd9afbeeb9c3491264aa9fab2d3b4a 

Meaning, that from your example, you should be able to do the following
`feature_formatter = PrettyHTMLFormatter(StreamOpener("second.html"), context.config, feature)`
and that should be all, the feature would be loaded withing the formatter init.

But as was said, this is not really an intended way to use behave, and we should not be hacking it on formatter side even though it is possible. Please use it in the intended way.

If there is something else you would like to include in the #97 let me know. As far as I know it should resolve issues with behave>=1.3.0

While pseudo steps still work when set in `behave.ini` my use case of enabling it and disabling it for specific tag in environment is no longer functional. We will redo this functionality later and decouple it from scenarios in the future.

**Comment by Kory291** [comment]
I'm not missing anything.
